config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :comments, only: [:create, :destroy, :edit, :update]
  resources :posts, only: [:index, :show, :create, :destroy, :edit, :update] do
    member do
      post '/like', to: "likes#create", as: "like"
      delete '/like', to: "likes#destroy", as: "unlike"
    end
  end

  post '/follows', to: "follows#create", as: "follow"
  delete '/follows', to: "follows#destroy", as: "unfollow"

  get '/profile/:id', to: "users#show", as: "user"
  get '/profile/:id/followings', to: "users#followings", as: "following"
  get '/profile/:id/followers', to: "users#followers", as: "followers"
  post '/users/search', to: "users#search", as: :search
  get '/users/search', to: "users#search"

  devise_for :users, :controllers => { registrations: 'registrations' }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  acts_as_commentable
  validates :user, :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
   # flash[:notice] = "sucesso";
    @user = current_user    #pega o usuario atual
     @post = Post.new
    posts = @user.posts.map {|post| post}
    @user.all_following.each { |user| user.posts.each{|post| posts << post } }
    @posts = (posts.sort_by! { |post| post.created_at }).reverse
    @posts = @posts.paginate(:page => (params[:page] || 1), :per_page => 10)

    respond_to do |format|
      format.html
      format.js
    end

  end

   def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.json { render json: @post, status: :created }
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.js   { render :file => "/app/views/posts/show.js.erb" }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.html { redirect_to posts_path }
      end
    end
  end

  def show
    @comment = Comment.new #visualiza o post
    @comments = @post.comments #pega todos os comentarios
  end

  def destroy
    @post.destroy #deleta o post
 
    respond_to do |format|
      format.json { head :no_content } #vazio deu certo
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' } #sucesso
    end
  end

  def edit
    @user = current_user    #pega o usuario atual
    posts = current_user.posts.map {|post| post} #pega todos os posts do usuario (transforma num array de posts)
    current_user.all_following.each { |user| user.posts.each{|post| posts << post } } #pega todos os usuarios que segue
    @posts = posts.sort_by &:created_at #ordena por data de criacao mostrando o ultimo post

  end

  def update

    respond_to do |format|  #se salvar o post rendeniza
       if @post.update(post_params)
        format.json { render json: @post, status: :created }
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' } #sucesso
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.html { redirect_to posts_path }
      end
    end
  end

  private
 
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
       params.require(:post).permit(:body).merge(user: current_user)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="row">
  <div class="col m12">
    <div class="row">
    	 <div class="row">
          <div class="col m12">
            <h5>Edit Post</h5>
          </div>
        </div>
      <div class="card hoverable">
        <div class="card-content">
          <div class="row">
            <div class="col m12">
            	<%= form_for @post do |f| %>
                <div class="input-field">
                  <%= f.text_area :body, placeholder: "What are you thinking about?", class: "materialize-textarea col l9" %>
                </div>
                <%= f.submit "Send", class: "btn red lighten-2" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
     
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col s12 m12 l3">
    <div class="row">
      <%= render 'shared/userinfo' %>
    </div>
  </div>
  <div class="col l1"></div>
  <div class="col l8 s12 page-content center">
    <div class="row">
      <div class="card hoverable">
        <div class="card-content">
          <div class="row">
            <div class="col m12">
               <%= form_for @post, url: "/posts", :method => "post", remote: true do |f| %>
              <div class="input-field">
                <%= f.text_area :body, placeholder: "What are you thinking about?", class: "materialize-textarea col l9" %>
              </div>
              <%= f.submit "Send", class: "btn red lighten-2" %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <button class="btn-floating reload blue">
          <i class="material-icons" style="font-size: 24px">replay</i>
        </button>
    </div>
  

    <div class="row" id="posts">
      <% @posts.each do |post| %>
        <%= render 'shared/post', post: post %>
      <% end %>
    </div>

    <div class="row">
      <div class="preloader-wrapper big active load" style="display: none">
        <div class="spinner-layer spinner-blue-only">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div><div class="gap-patch">
            <div class="circle"></div>
          </div><div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.js.erb
<% @posts.each do |post| %>
  $("#posts").append("<%= j render 'shared/post', post: post %>");
<% end %>

app/views/posts/show.html.erb
<div class="row center">
    <%= render 'shared/post',post: @post %>
  </div>

  <div class="row">
    <div class="card hoverable">
      <div class="card-content">
        <div class="row">
          <div class="col m12">
            <h5>Comments</h5>
          </div>
        </div>

        <div class="row">
          <div class="col m12">
            <%= form_for @comment, url: "/comments", :method => "post" do |f| %>
              <div class="input-field">
                <%= f.text_area :comment, placeholder: "What are you thinking about this post?", class: "materialize-textarea col l9" %>
                <%= f.hidden_field :post_id, value: @post.id %>
              </div>
              <%= f.submit "Comment", class: "btn red lighten-2" %>
            <% end %>
          </div>
        </div>

          <% @comments.reverse_each do |comment| %>
            <div class="divider"></div>

            <div class="comment">
              <div class="row">
                <div class="col m2">
                  <img src="<%= comment.user.avatar.thumb.url %>" alt="" class="circle responsive-img user-image">
                </div>
                <div class="col m7">
                  <a href="/users/<%= comment.user_id %>" class="comment-user-name grey-text text-darken-2">
                    <p><%= comment.user.name %></p>
                  </a>
                </div>
                <div class="col m2">
                  <b class="grey-text right"><%= comment.created_at.strftime('%Hh%M') %></b>
                </div>
           <%= link_to edit_comment_path(comment) do %>
           <i class="material-icons">edit</i>
            <% end %>
            <%= link_to comment_path(comment), method: "delete" do %>
            <i class="material-icons post-options">delete</i>
          <% end %>
              </div>
              <div class="row">
                <div class="col m12">
                  <p class="comment-content"><%= comment.comment %></p>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.js.erb
$("#posts").prepend("<%= j render 'shared/post', post: @post %>");